# Generated by Django 3.1 on 2020-09-14 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('perfil', models.ManyToManyField(to='perfil.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='Reacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('peso', models.CharField(max_length=50)),
                ('data', models.DateField(auto_now_add=True)),
                ('perfil', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil')),
                ('postagem', models.ManyToManyField(to='perfil.Postagem')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('data', models.DateField(auto_now_add=True)),
                ('senha', models.CharField(max_length=16)),
                ('perfil', models.ManyToManyField(to='perfil.Perfil')),
            ],
        ),
        migrations.DeleteModel(
            name='AddProfile',
        ),
        migrations.AddField(
            model_name='comentario',
            name='perfil',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='perfil.perfil'),
        ),
        migrations.AddField(
            model_name='comentario',
            name='postagem',
            field=models.ManyToManyField(to='perfil.Postagem'),
        ),
    ]
